export const posts = [
        {
            id: '1',
            image: 'https://i1.wp.com/elprismadefer.com/wp-content/uploads/2020/03/blog18.jpg?fit=800%2C600',
            url: '',
            title: 'El Cairo, la ciudad del caos | El Prisma de Fer',
            description: 'El Cairo, ciudad del caos es una reflexión sobre mi visita a la capital Egipcia. Cómo es la ciudad, que hacer en El Cairo, ¿es segura? y más en esta guía.',
            lat: '30.048192',
            lng: '31.236148',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:23, name:'Egipto'},
            tags: ['Guia']
        },
        {
            id: '2',
            image: 'https://i2.wp.com/elprismadefer.com/wp-content/uploads/2019/02/argentina06.jpg?fit=1200%2C900',
            url: 'http://elprismadefer.com/sudamerica/argentina/cataratas-del-iguazu-una-de-las-7-maravillas-naturales/',
            title: 'Cataratas del Iguazú, una de las 7 maravillas naturales | El Prisma de Fer',
            description: 'Guía completa sobre como visitar las Cataratas del Iguazú desde el lado Argentino y Brasilero. Como llegar en transporte público, excursiones y más.',
            lat: '-25.666360',
            lng: '-54.450301',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:5, name:'Argentina'},
            tags: ['Guia', 'Trekking', 'Maravillas']
        },
        {
            id: '3',
            image: 'https://i0.wp.com/elprismadefer.com/wp-content/uploads/2019/02/argentina08.jpg?fit=1200%2C799',
            url: 'http://elprismadefer.com/sudamerica/argentina/como-visitar-el-glaciar-perito-moreno-en-argentina/',
            title: 'Como visitar el Glaciar Perito Moreno en Argentina | El Prisma de Fer',
            description: 'Guía completa para visitar el Glaciar Perito Moreno en Argentina. Como llegar al Glaciar por tu cuenta. Que tipo de Actividades se pueden en el Glaciar.',
            lat: '-50.470944',
            lng: '-73.040776',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:5, name:'Argentina'},
            tags: ['Guia', 'Trekking']
        },
        {
            id: '4',
            image: 'https://i0.wp.com/elprismadefer.com/wp-content/uploads/2019/02/ecuador29.jpg?fit=1200%2C703',
            url: 'http://elprismadefer.com/sudamerica/ecuador/que-hacer-en-banos-de-agua-santa-ecuador/',
            title: 'Que hacer en Baños de Agua Santa, Ecuador | El Prisma de Fer',
            description: 'Guía completa sobre lo que podemos hacer en Baños de Agua Santa en Ecuador. Ruta de las Cascadas, Casa del arbol, Vistas al Volcán Tungurahua y más.',
            lat: '-1.396928',
            lng: '-78.425946',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:103, name:'Ecuador'},
            tags: ['Guia']
        },
        {
            id: '5',
            image: 'https://i2.wp.com/elprismadefer.com/wp-content/uploads/2019/02/ecuador01.jpg?fit=1200%2C779',
            url: 'http://elprismadefer.com/sudamerica/ecuador/un-dia-en-el-parque-nacional-cotopaxi-en-ecuador/',
            title: 'Un día en el Parque Nacional Cotopaxi en Ecuador. | El Prisma de Fer',
            description: 'Guía sobre como conocer el Parque Nacional Cotopaxi en Ecuador. Conviene ir por tu cuenta o con excursión. Que hacer y que esperar del tour.',
            lat: '-0.700445',
            lng: '-78.432561',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:103, name:'Ecuador'},
            tags: ['Guia']
        },
        {
            id: '6',
            image: 'https://i1.wp.com/elprismadefer.com/wp-content/uploads/2019/02/vietnam13.jpg?fit=1200%2C900',
            url: 'http://elprismadefer.com/asia/vietnam/sapa-y-sus-paisajes-de-arrozales-vietnam/',
            title: 'Sapa y sus paisajes de arrozales, Vietnam | El Prisma de Fer',
            description: 'Guía relato sobre que hacer en Sapa en 3 días. Trekking por sus campos de arrozales, andar en moto por sus rutas y disfrutar de los paisajes de ensueño.',
            lat: '22.335646',
            lng: '103.842187',
            show: false,
            author: { thumbnail: '/images/ferca84.jpg', name: 'elPrismaDeFer'},
            pais: {id:15, name:'Vietnam'},
            tags: ['Guia']
        }
    ]